<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite ignored="0" hostname="ViridianGaming" failures="1" tests="1" name="Positive Tests" time="8.721" errors="0" timestamp="2024-08-28T22:12:26 IST">
  <testcase classname="viridiantooth34.tests.StandAloneTest" name="addToCart" time="5.716">
    <failure type="java.lang.AssertionError" message="Order was not placed! expected [THANKYOU FOR THE ORDER._] but found [THANKYOU FOR THE ORDER.]">
      <![CDATA[java.lang.AssertionError: Order was not placed! expected [THANKYOU FOR THE ORDER._] but found [THANKYOU FOR THE ORDER.]
at viridiantooth34.tests.StandAloneTest.addToCart(StandAloneTest.java:64)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1597)
... Removed 30 stack frames]]>
    </failure>
  </testcase> <!-- addToCart -->
</testsuite> <!-- Positive Tests -->
